openai:
  AGENT_GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_API_KEY: "sk-lAWdJVGgMJikTuhW2PBIgwecI6Gwg0gdM3xKVxwYDiOW98ra"
  PROXY: "https://api.juheai.top/v1"

tool:
  tool_list:
    - "TemporalTool_cpu"
    - "CountingTool_cpu"
    - "ReasonFinder_cpu"
    - "HowSeeker_cpu"
    - "DescriptionTool_cpu"
    - "DefaultTool_cpu"

mannual_cache_file: "cache/gpt35_cache_run_on_question.pkl"
use_cache: True

dataset: "nextqa"
video_path_base: "/share_data/NExT-QA/NExTVideo"
anno_path: "/share_data/NExT-QA/dataset/nextqa/train.csv"
num_examples_to_run: 1
start_num: 0
quids_to_exclude: ["6595307655_4"]

overwrite_mem: False

seed: 12345

output_path: "output/nextqa/"

recursion_limit: 24
