inference_config_path: "config/inference/inference_gpt35.yaml"
mannual_cache_file: "cache/gpt35_cache_fix_1.pkl"
dataset: "nextqa"
video_path_base: "/share_data/NExT-QA/NExTVideo"
anno_path: "/share_data/NExT-QA/dataset/nextqa/train.csv"
overwrite_mem: False
seed: 12345
output_file: "output/nextqa/nextqa_output.json"
num_examples_to_run: 100
start_num: 0
use_cache: True
quids_to_exclude: ["6595307655_4"]
recursion_limit: 24
