inference_config_path: "config/inference/inference_gpt35.yaml"
mannual_cache_file: "cache/gpt35_cache_simple.pkl"
dataset: "nextqa"
video_path_base: "/share_data/NExT-QA/NExTVideo"
anno_path: "/share_data/NExT-QA/dataset/nextqa/train.csv"
skip_mem_build: True
with_two_mem: True
seed: 12345
max_answer: 3
max_try: 7
output_file: "output/nextqa/nextqa_output.json"
num_examples_to_run: 100
start_num: 0
use_cache: False
