# config.yaml
openai:
  AGENT_GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_API_KEY: "sk-lAWdJVGgMJikTuhW2PBIgwecI6Gwg0gdM3xKVxwYDiOW98ra"
  PROXY: "https://api.juheai.top/v1"

memory:
  db_version: 2
  step: 30  # 这个应该是 video stride
  memory_list:
    - "VideoInstanceUnderstanding_cuda:0"
    - "VideoTemporalUnderstanding_cuda:0"

tool:
  TOP_K: 2
  tool_list:
    - "TemporalTool_cpu"
    - "CountingTool_cpu"
    - "ReasonFinder_cpu"
    - "HowSeeker_cpu"
    - "DescriptionTool_cpu"
    - "DefaultTool_cpu"

